### ISSUE TITLE
Mounting rw doesn't work

### ISSUE THREAD

**Issue by feklee** [ghollingworth/overlayfs#2]
I do:

    pi@raspberrypi:~ $ sudo overctl -w
    pi@raspberrypi:~ $ sudo systemctl reboot

After the reboot:

    pi@raspberrypi:~ $ sudo overctl -s
    / is currently mounted RO and will be mounted RW on next boot

It's possible that something went wrong because I had to run `sudo ./overlayfs.sh` twice: At first it couldn't finish as `initramfs-tools` were not installed.

Details:

    pi@raspberrypi:/boot $ bash -x `which overctl` -s
    + BOOT=/boot
    + CMDLINE=cmdline.txt
    + CMDLINE_RO=cmdline.txt.overlay
    + CMDLINE_RW=cmdline.txt.orig
    + '[' -s = --help -o -s = -h ']'
    + cd /boot
    + for file in $CMDLINE $CMDLINE_RO $CMDLINE_RW
    + '[' -r cmdline.txt ']'
    + for file in $CMDLINE $CMDLINE_RO $CMDLINE_RW
    + '[' -r cmdline.txt.overlay ']'
    + for file in $CMDLINE $CMDLINE_RO $CMDLINE_RW
    + '[' -r cmdline.txt.orig ']'
    + case "$1" in
    + action=status
    ++ cat cmdline.txt
    + line_active='boot=overlay dwc_otg.lpm_enable=0 console=serial0,115200 console=tty1 root=PARTUUID=07aaa040-02 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait'
    ++ cat cmdline.txt.overlay
    + line_ro='boot=overlay boot=overlay dwc_otg.lpm_enable=0 console=serial0,115200 console=tty1 root=PARTUUID=07aaa040-02 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait'
    ++ cat cmdline.txt.orig
    + line_rw='boot=overlay dwc_otg.lpm_enable=0 console=serial0,115200 console=tty1 root=PARTUUID=07aaa040-02 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait'
    + '[' 'boot=overlay dwc_otg.lpm_enable=0 console=serial0,115200 console=tty1 root=PARTUUID=07aaa040-02 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait' = 'boot=overlay boot=overlay dwc_otg.lpm_enable=0 console=serial0,115200 console=tty1 root=PARTUUID=07aaa040-02 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait' ']'
    + '[' 'boot=overlay dwc_otg.lpm_enable=0 console=serial0,115200 console=tty1 root=PARTUUID=07aaa040-02 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait' = 'boot=overlay dwc_otg.lpm_enable=0 console=serial0,115200 console=tty1 root=PARTUUID=07aaa040-02 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait' ']'
    + state=RW
    + '[' status = status ']'
    ++ mount
    ++ grep ' on / '
    + str='overlay on / type overlay (rw,noatime,lowerdir=/lower,upperdir=/upper/data,workdir=/upper/work)'
    + echo overlay on / type overlay '(rw,noatime,lowerdir=/lower,upperdir=/upper/data,workdir=/upper/work)'
    + grep -q overlay
    + echo -n '/ is currently mounted RO'
    / is currently mounted RO+ echo ' and will be mounted RW on next boot'
     and will be mounted RW on next boot
    + exit 0

Files:

    pi@raspberrypi:~ $ cat /boot/cmdline.txt
    boot=overlay dwc_otg.lpm_enable=0 console=serial0,115200 console=tty1 root=PARTUUID=07aaa040-02 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait
    pi@raspberrypi:~ $ cat /boot/cmdline.txt.orig
    boot=overlay dwc_otg.lpm_enable=0 console=serial0,115200 console=tty1 root=PARTUUID=07aaa040-02 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait
    pi@raspberrypi:~ $ cat /boot/cmdline.txt.overlay
    boot=overlay boot=overlay dwc_otg.lpm_enable=0 console=serial0,115200 console=tty1 root=PARTUUID=07aaa040-02 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait

Yes, the `boot=overlay` in `cmdline.orig` looks not good. I'll try to remove that. (requires `sudo mount -o remount,rw /boot/`)

**Comment by ghollingworth** [comment]
I'm wondering if this is because the /boot is read-only?  I know I added code to set it to be read-only when setting up the overlayfs.  But don't remember adding code in overctl to undo / redo this...

Gordon

**Comment by feklee** [comment]
The script should be designed to be run again without breaking. In the end I did the steps manually following [yagebru's tutorial](https://yagrebu.net/unix/rpi-overlay.md). Manual setup is not particularly hard, and one sees what's happening and can fix issues along the way.

**Comment by randyoo** [comment]
@ghollingworth I experienced the same symptoms as @feklee . 

I found that in my /boot partition, the cmdline.txt had boot=overlay in it twice. cmdline.txt had it in there at least once, and cmdline.txt.overlay had it three times! I'm not sure how it got to that state, but I resolved it by removing "boot=overlay" completely from cmdline.txt and .orig, and removed the extra instances in .overlay.

Now it seems to work fine. Thanks for this project, by the way!

**Comment by ghollingworth** [comment]
I would suggest people no longer use this repo for the overlayfs, instead using the raspi-config utility.

You can do this from the command line or from the gui (the nonint function allows you to run it from a script)

**Comment by randyoo** [comment]
The raspi-config utility is actually what led me here. I discovered the option in raspi-config on a different Pi running Buster, but since the option doesn't exist in Stretch, and I didn't really care to upgrade the entire OS, I looked into overlay fs, and ended up here. I had already solved my problem, and only came here to comment in the hopes of helping anyone else with the same issue.
