### ISSUE TITLE
Feature request: Allow making changes without rebooting via chroot

### ISSUE THREAD

**Issue by esbennn** [ghollingworth/overlayfs#4]
This is great! 

I have wanted a sort official variant of this feature for so long. 

I have previously used another [overlayroot](https://github.com/chesty/overlayroot) which seems to work more or less the same. 
The great thing about that one is, that et includes a script to perform "rootwork". I'm not that strong in bash, but it seems to remount the actual fs to another point, and the do a chroot to there. That way you can perform simple changes such as changing wifi credentials without having to reboot twice. Actually, you can even transfer files over ssh.

It would be really cool with a feature like that in this overlayfs solution, since this is now integrated into `raspi-config` (right?), and therefore is more "official".

**Comment by ghollingworth** [comment]
Yeah, now all support is through the official raspi-config script
